name: MacOSX BigSur brew build
on:
  release:
    types: [published]
jobs:
  checkout-repo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-12]
    steps:
      - name: Checkout upstream metacall.rb brew install
        uses: actions/checkout@v3
      - run: |
         chmod +x ./build.sh
         ./build.sh

